// Package nrf implements the Network Repository Function.
//
// The NRF provides two services defined in TS 29.510:
//   - NF Management  (nnrf-nfm): register, update, deregister NF instances
//   - NF Discovery   (nnrf-disc): query for NF instances by type/PLMN/slice
//
// All interfaces are HTTP/1.1 (upgradeable to HTTP/2) with JSON bodies,
// following the OpenAPI definitions in TS 29.510.
//
// Ref: TS 29.510 — 5G System; Network Function Repository Services
// Ref: TS 23.501 §6.2.7 — NRF
package nrf

import "time"

// NFType represents the type of a Network Function.
// Ref: TS 29.510 §6.1.6.3.3 — NFType enumeration
type NFType string

const (
	NFTypeAMF  NFType = "AMF"
	NFTypeSMF  NFType = "SMF"
	NFTypeUPF  NFType = "UPF"
	NFTypeUDM  NFType = "UDM"
	NFTypeAUSF NFType = "AUSF"
	NFTypePCF  NFType = "PCF"
	NFTypeNRF  NFType = "NRF"
	NFTypeNSSF NFType = "NSSF"
)

// NFStatus represents the current status of a registered NF instance.
// Ref: TS 29.510 §6.1.6.3.4 — NFStatus enumeration
type NFStatus string

const (
	NFStatusRegistered   NFStatus = "REGISTERED"
	NFStatusSuspended    NFStatus = "SUSPENDED"
	NFStatusUnregistered NFStatus = "UNDISCOVERABLE"
)

// Snssai represents a Single Network Slice Selection Assistance Information.
// SST (Slice/Service Type) + optional SD (Slice Differentiator).
// Ref: TS 23.003 §28.4 / TS 29.510 §6.1.6.2.24
type Snssai struct {
	Sst int    `json:"sst"`          // 0-255; 1=eMBB 2=URLLC 3=MIoT
	Sd  string `json:"sd,omitempty"` // 6 hex chars, optional
}

// NFService describes a single service exposed by an NF instance.
// e.g. the AMF exposes "namf-comm", "namf-evts", "namf-mt" etc.
// Ref: TS 29.510 §6.1.6.2.27
type NFService struct {
	ServiceInstanceID string   `json:"serviceInstanceId"`
	ServiceName       string   `json:"serviceName"` // e.g. "namf-comm"
	Versions          []string `json:"versions"`    // e.g. ["v1"]
	Scheme            string   `json:"scheme"`      // "http" or "https"
	NFServiceStatus   NFStatus `json:"nfServiceStatus"`
	APIPrefix         string   `json:"apiPrefix,omitempty"`
}

// NFProfile is the full description of a Network Function instance.
// This is what an NF POSTs to the NRF when registering, and what
// the NRF returns in discovery responses.
//
// Ref: TS 29.510 §6.1.6.2.2 — NFProfile data type
type NFProfile struct {
	// NfInstanceID is the UUID identifying this NF instance.
	// Generated by the NF itself at startup.
	// Ref: TS 29.510 §6.1.3.2
	NfInstanceID string `json:"nfInstanceId"`

	// NfType identifies what kind of NF this is.
	NfType NFType `json:"nfType"`

	// NfStatus is the current operational status.
	NfStatus NFStatus `json:"nfStatus"`

	// PlmnList is the list of PLMNs this NF serves.
	// Ref: TS 29.510 §6.1.6.2.2
	PlmnList []string `json:"plmnList,omitempty"`

	// SNssais is the list of slices this NF supports.
	SNssais []Snssai `json:"sNssais,omitempty"`

	// Fqdn is the fully-qualified domain name of this NF (optional).
	Fqdn string `json:"fqdn,omitempty"`

	// IPv4Addresses are the IP addresses of this NF instance.
	IPv4Addresses []string `json:"ipv4Addresses,omitempty"`

	// AllowedNfTypes lists which NF types are allowed to discover this NF.
	// Empty means all NF types can discover it.
	AllowedNfTypes []NFType `json:"allowedNfTypes,omitempty"`

	// NfServices are the individual service endpoints this NF exposes.
	NfServices []NFService `json:"nfServices,omitempty"`

	// Capacity is the NF's load capacity (0-65535).
	// Used by NRF for weighted discovery responses.
	Capacity int `json:"capacity,omitempty"`

	// RegisteredAt is set by the NRF when the profile is stored.
	// Not part of the spec — internal bookkeeping.
	RegisteredAt time.Time `json:"registeredAt,omitempty"`

	// LastHeartbeat is updated each time the NF sends a heartbeat.
	// Ref: TS 29.510 §5.3.2.4 — NF Heartbeat
	LastHeartbeat time.Time `json:"lastHeartbeat,omitempty"`
}

// DiscoveryResponse is returned by the NF Discovery service.
// Ref: TS 29.510 §6.1.6.2.36 — SearchResult
type DiscoveryResponse struct {
	ValidityPeriod int         `json:"validityPeriod"` // seconds
	NfInstances    []NFProfile `json:"nfInstances"`
}

// ErrorResponse is the standard problem detail returned on errors.
// Ref: TS 29.571 §5.2.6 — ProblemDetails
type ErrorResponse struct {
	Type     string `json:"type,omitempty"`
	Title    string `json:"title"`
	Status   int    `json:"status"`
	Detail   string `json:"detail,omitempty"`
	Instance string `json:"instance,omitempty"`
}
