sequenceDiagram
  autonumber
  participant UE
  participant gNB
  participant AMF
  participant SMF
  participant UPF
  participant NRF

  UE->gNB: RRC Setup Complete<br/><small>[TS 38.331 §5.3.3.4]</small> (+9101ms)
  gNB->AMF: N2: Initial UE Message<br/><small>[TS 38.413 §9.2.5.1]</small> (+9101ms)
  AMF->gNB: N2: Downlink NAS Transport<br/><small>[TS 38.413 §9.2.5.2]</small> (+9103ms)
  gNB->UE: RRC DL Information Transfer<br/><small>[TS 38.331 §5.3.3.5]</small> (+9104ms)
  AMF->gNB: N2: Downlink NAS Transport<br/><small>[TS 38.413 §9.2.5.2]</small> (+9312ms)
  gNB->UE: RRC DL Information Transfer<br/><small>[TS 38.331 §5.3.3.5]</small> (+9312ms)
  UE->gNB: RRC Setup Complete<br/><small>[TS 38.331 §5.3.3.4]</small> (+151781ms)
  gNB->AMF: N2: Initial UE Message<br/><small>[TS 38.413 §9.2.5.1]</small> (+151781ms)
  AMF->gNB: N2: Downlink NAS Transport<br/><small>[TS 38.413 §9.2.5.2]</small> (+151783ms)
  gNB->UE: RRC DL Information Transfer<br/><small>[TS 38.331 §5.3.3.5]</small> (+151783ms)
  AMF->gNB: N2: Downlink NAS Transport<br/><small>[TS 38.413 §9.2.5.2]</small> (+151988ms)
  gNB->UE: RRC DL Information Transfer<br/><small>[TS 38.331 §5.3.3.5]</small> (+151988ms)
